### ISSUE TITLE
 Cannot be installed in Windows environment. (Probably because of symlink)

### ISSUE THREAD

**Issue by nodai2hITC** [vaiorabbit/raylib-bindings#1]
In my Windows environment, I can install 0.0.1 without any problem, but I cannot install 0.0.2 and 0.0.3. Not only the installation, but also downloading the gem file and trying to `gem unpack` does not work.

I think this is because the files `libraylib.400.dylib` and `libraylib.dylib` are symlinked, so cannot be unpacked under Windows.

```
> gem install raylib-bindings --verbose --backtrace

ERROR:  While executing gem ... (Errno::EINVAL)
    Invalid argument @ rb_file_s_symlink - (libraylib.4.0.0.dylib, E:/tools/Ruby/ruby3.0-64/lib/ruby/gems/3.0.0/gems/raylib-bindings-0.0.3/lib/libraylib.400.dylib)
        E:/tools/Ruby/ruby3.0-64/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:446:in `symlink'
```
rubygems version: 3.3.5 (latest version)

I have confirmed that it can be deployed without problems in a Linux environment.

(By the way, are there any plans to support the 32-bit environment?)

**Comment by vaiorabbit** [comment]
The commit https://github.com/vaiorabbit/raylib-bindings/commit/f5b2775262d786573955c6a47c8dbfcf894fe021 removes symlinks and fixes error seen on `gem install`. Thanks for reporting.

> (By the way, are there any plans to support the 32-bit environment?)

I regret to say that there is no plan to provide pre-built binaries for environments I do not own or hardly use.

**Comment by nodai2hITC** [comment]
I have confirmed that I can install it.
Thank you!
