### ISSUE TITLE
raygui upstream problem

### ISSUE THREAD

**Issue by incompetentcoder** [vaiorabbit/raylib-bindings#2]
Hello. First of all thanks for this, love it!
Since raygui upstream changed their headers for text for guiscrollpanel git head doesn't build for me, so submodule also doesn't build. I had to revert last 3 upstream commits in raygui submodule to get it to build. Might want to check out a tag instead

**Comment by vaiorabbit** [comment]
Thank you. https://github.com/vaiorabbit/raylib-bindings/commit/854b8aaaada95aba8c43f374cbda13c539bbdc16 reverts the change and refers to raygui 3.1.
