### ISSUE TITLE
DrawTriangleFan: :pointer argument is not a valid pointer

### ISSUE THREAD

**Issue by IvanShamatov** [vaiorabbit/raylib-bindings#7]
Hi, @vaiorabbit, thanks a lot for your work making these bindings to Raylib (the only i managed to make working:)
Can you please help me with the understanding, what is wrong with this example:
```ruby
require_relative 'setup_dll'

SetTargetFPS(60)
InitWindow(300, 300, "RayCasting")
  points = [
    Vector2.create(150, 300),
    Vector2.create(0, 0),
    Vector2.create(300, 0)
  ]
  until WindowShouldClose()
    ClearBackground(BLACK)
    DrawTriangleFan(points, points.size, Fade(PINK, 0.1))
  end
CloseWindow()
```
Error looks like that, and that's it:
```bash
ex.rb:14:in `DrawTriangleFan': :pointer argument is not a valid pointer (ArgumentError)
```

It might be I misunderstand how to use `FFI::Pointers`, but according to signature, the pointer to an array should be passed. 
How can I do that? Thanks in advance

**Comment by vaiorabbit** [comment]
Hi. In this case we need to pass the data in a tightly packed format. So

```ruby
SetTargetFPS(60)
InitWindow(300, 300, 'Test')
  points = [ # counter-clockwise order
    Vector2.create(0, 0),
    Vector2.create(150, 300),
    Vector2.create(300, 0),
  ]

  points_buffer = FFI::MemoryPointer.new(FFI::NativeType::FLOAT32.size * (2 * points.size))
  points_buffer.put_array_of_float32(0, points.map(&:to_a).flatten!)

  until WindowShouldClose()
    BeginDrawing()
    ClearBackground(BLACK)
    DrawTriangleFan(points_buffer, points.size, Fade(PINK, 1.0))
    EndDrawing()
  end
CloseWindow()
```

or

```ruby
SetTargetFPS(60)
InitWindow(300, 300, 'Test')
  points = [ # counter-clockwise order
    Vector2.create(0, 0),
    Vector2.create(150, 300),
    Vector2.create(300, 0),
  ]

  points_buffer = points.map(&:to_a).flatten.pack("F*")

  until WindowShouldClose()
    BeginDrawing()
    ClearBackground(BLACK)
    DrawTriangleFan(points_buffer, points.size, Fade(PINK, 1))
    EndDrawing()
  end
CloseWindow()
```

would work fine.

<img src="https://github.com/vaiorabbit/raylib-bindings/assets/1689749/af6df369-a22f-4785-bb76-72970ad1a8aa" width="400" />


You can find another example here:
* https://github.com/vaiorabbit/raylib-bindings/blob/fa5b8f21b869e9fdea1769c0ea2adae0d6eb48a5/examples/shapes_splines_drawing.rb#L42
* https://github.com/vaiorabbit/raylib-bindings/blob/fa5b8f21b869e9fdea1769c0ea2adae0d6eb48a5/examples/shapes_splines_drawing.rb#L45

**Comment by IvanShamatov** [comment]
Thanks a lot! 🙇🏼
