### ISSUE TITLE
Bunnymark Optimized

### ISSUE THREAD

**Issue by Nathan-MV** [vaiorabbit/raylib-bindings#8]
I noticed the new `textures_bunnymark_optimized.rb` so i would like to suggest making a constant to disable random movement and random color as they represent unusual use cases. It increased the performance from drawing 12k at 60 fps to 40k at 60 fps here

Optionally you could also multiply the bunny speed by GetFrameTime() * 60 so that they move at the same speed regardless of the fps

**Comment by vaiorabbit** [comment]
This change would diverge this sample from the behavior of the original code.
