### ISSUE TITLE
Instructions for packaging a game built with raylib-bindings?

### ISSUE THREAD

**Issue by preetpalS** [vaiorabbit/raylib-bindings#9]
Hi,

If there were instructions for packaging games on the README, it would be helpful. For Windows, I was able to build a Windows executable with the [ocran](https://github.com/Largo/ocran) gem  (Ocran 1.3.15) using Ruby 3.3 (ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x64-mingw-ucrt]). I am unfamiliar with packaging Ruby applications for other operating systems.

This is only a suggestion, but I mainly created this issue so others could know that there is a way to package their games into executables using the the **ocran** gem quite easily (`ocran --windows --gemfile Gemfile main.rb`).

Thanks.

**Comment by vaiorabbit** [comment]
Personally I've never tried to pack game scripts, and don't have any plan to do so. And it seems there's no stable, reliable and maintained way to pack ruby scripts as an executable for several platforms. I think it's user's own task to search correct way to pack their games.
